export enum Claim {
  CLAIM_CREATE = 'claim.create',
  CLAIM_READ = 'claim.read',
  CLAIM_UPDATE = 'claim.update',
  CLAIM_DELETE = 'claim.delete',
  USER_CREATE = 'user.create',
  USER_READ = 'user.read',
  USER_UPDATE = 'user.update',
  USER_DELETE = 'user.delete',
  CITY_CREATE = 'city.create',
  CITY_READ = 'city.read',
  CITY_UPDATE = 'city.update',
  CITY_DELETE = 'city.delete',
  FOO_CREATE = 'foo.create',
  FOO_READ = 'foo.read',
  FOO_UPDATE = 'foo.update',
  FOO_DELETE = 'foo.delete',
  BAR_CREATE = 'bar.create',
  BAR_READ = 'bar.read',
  BAR_UPDATE = 'bar.update',
  BAR_DELETE = 'bar.delete',
}
